---
title: "Green transition most developed in secondary sector"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = FALSE}
library(tidyverse)
library(psych)
library(ggplot2)
library(DescTools)

initial.data <- read.table("~/Desktop/IMB/multivariateAnalysis/rprogramming/anketaFinal.csv", header=TRUE, sep=";", dec=",", na.strings=c("-2", "-3", "-4", "-5"))

select1 <- initial.data %>%
  select(Q20, Q1, Q2a, Q2b, Q2c, Q2d, Q2e, Q2f, Q2g, Q2h, Q2i, Q2j) %>% 
  mutate(Q20=replace(Q20, Q20 == -1, 2)) %>% 
  mutate(Q2a=replace(Q2a, Q2a == -1, 1)) %>% 
  mutate(Q2b=replace(Q2b, Q2b == -1, 1)) %>% 
  mutate(Q2c=replace(Q2c, Q2c == -1, 1)) %>% 
  mutate(Q2d=replace(Q2d, Q2d == -1, 1)) %>% 
  mutate(Q2e=replace(Q2e, Q2e == -1, 1)) %>% 
  mutate(Q2f=replace(Q2f, Q2f == -1, 1)) %>% 
  mutate(Q2g=replace(Q2g, Q2g == -1, 1)) %>% 
  mutate(Q2h=replace(Q2h, Q2h == -1, 1)) %>% 
  mutate(Q2i=replace(Q2i, Q2i == -1, 1)) %>% 
  mutate(Q2j=replace(Q2j, Q2j == -1, 1)) %>% 
  drop_na()

select1$Q20Factor <- factor(select1$Q20,
                            levels = c(1:14),
                            labels = c("Primary", "Secondary", "Secondary", "Secondary", "Secondary", "Tertiary", "Tertiary", "Tertiary", "Tertiary", "Tertiary", "Tertiary", "Tertiary",  "Tertiary",  "Tertiary"))



select1$Q2aFactor <- factor(select1$Q2a,
                            levels = c(2:5),
                            labels = c("1 year", "2-5 years", "2-5 years", "5+ years"))

select1$Q2bFactor <- factor(select1$Q2b,
                            levels = c(2:5),
                            labels = c("1 year", "2-5 years", "2-5 years", "5+ years"))

select1$Q2cFactor <- factor(select1$Q2c,
                            levels = c(2:5),
                            labels = c("1 year", "2-5 years", "2-5 years", "5+ years"))

select1$Q2dFactor <- factor(select1$Q2d,
                            levels = c(2:5),
                            labels = c("1 year", "2-5 years", "2-5 years", "5+ years"))

select1$Q2eFactor <- factor(select1$Q2e,
                            levels = c(2:5),
                            labels = c("1 year", "2-5 years", "2-5 years", "5+ years"))

select1$Q2fFactor <- factor(select1$Q2f,
                            levels = c(2:5),
                            labels = c("1 year", "2-5 years", "2-5 years", "5+ years"))

select1$Q2gFactor <- factor(select1$Q2g,
                            levels = c(2:5),
                            labels = c("1 year", "2-5 years", "2-5 years", "5+ years"))

select1$Q2hFactor <- factor(select1$Q2h,
                            levels = c(2:5),
                            labels = c("1 year", "2-5 years", "2-5 years", "5+ years"))

select1$Q2iFactor <- factor(select1$Q2i,
                            levels = c(2:5),
                            labels = c("1 year", "2-5 years", "2-5 years", "5+ years"))
```

# Recycling

```{r}
(recikliranje <- as.data.frame.matrix(table(select1$Q20Factor, select1$Q2aFactor)))
recikliranjedf <- data.frame(sector = select1$Q20Factor, duration = select1$Q2aFactor)
recikliranjedf <- recikliranjedf %>% drop_na()
recikliranjedfgroup <- recikliranjedf %>% 
  group_by(sector, duration) %>% 
  summarise(count = n())

ggplot(recikliranjedfgroup, aes(x=sector, y=duration)) + 
  geom_point(aes(size = count), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 20, guide = FALSE) +
  geom_text(aes(
    y = as.numeric(as.factor(duration)) - count/34, label = count),
    vjust = 2,
    colour = "black",
    size = 4
  ) + 
  xlab("Sector") + ylab("Duration of investment") +
  labs(caption=paste("Number of responses :",nrow(recikliranjedf)))

fisher.test(select1$Q20Factor, select1$Q2aFactor)
```

# Use of environmentally friendly materials

```{r}
(okolje <- as.data.frame.matrix(table(select1$Q20Factor, select1$Q2bFactor)))
okoljedf <- data.frame(sector = select1$Q20Factor, duration = select1$Q2bFactor)
okoljedf <- okoljedf %>% drop_na()
okoljedfgroup <- okoljedf %>% 
  group_by(sector, duration) %>% 
  summarise(count = n()) %>% 
  drop_na()

ggplot(okoljedfgroup, aes(x=sector, y=duration)) + 
  geom_point(aes(size = count), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 20, guide = FALSE) +
  geom_text(aes(
    y = as.numeric(as.factor(duration)) - count/34, label = count),
    vjust = 3,
    colour = "black",
    size = 4
  ) + 
  xlab("Sektor") + ylab("Duration of investment") +
  labs(caption=paste("Number of responses :",nrow(okoljedf)))

fisher.test(select1$Q20Factor, select1$Q2bFactor)
```

# Reduction of electricity consumption

```{r}
(energija <- as.data.frame.matrix(table(select1$Q20Factor, select1$Q2cFactor)))
energijadf <- data.frame(sector = select1$Q20Factor, duration = select1$Q2cFactor)
energijadf <- energijadf %>% drop_na()
energijadfgroup <- energijadf %>% 
  group_by(sector, duration) %>% 
  summarise(count = n()) %>% 
  drop_na()

ggplot(energijadfgroup, aes(x=sector, y=duration)) + 
  geom_point(aes(size = count), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 20, guide = FALSE) +
  geom_text(aes(
    y = as.numeric(as.factor(duration)) - count/34, label = count),
    vjust = 2,
    colour = "black",
    size = 4
  ) + 
  xlab("Sektor") + ylab("Duration of investment") +
  labs(caption=paste("Number of responses :",nrow(energijadf)))

fisher.test(select1$Q20Factor, select1$Q2cFactor)
```

# Reduction of drinking water consumption

```{r}
(voda <- as.data.frame.matrix(table(select1$Q20Factor, select1$Q2dFactor)))
vodadf <- data.frame(sector = select1$Q20Factor, duration = select1$Q2dFactor)
vodadf <- vodadf %>% drop_na()
vodadfgroup <- vodadf %>% 
  group_by(sector, duration) %>% 
  summarise(count = n()) %>% 
  drop_na()

ggplot(vodadfgroup, aes(x=sector, y=duration)) + 
  geom_point(aes(size = count), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 20, guide = FALSE) +
  geom_text(aes(
    y = as.numeric(as.factor(duration)) - count/34, label = count),
    vjust = 3,
    colour = "black",
    size = 4
  ) + 
  xlab("Sektor") + ylab("Duration of investment") +
  labs(caption=paste("Number of responses :",nrow(vodadf)))

fisher.test(select1$Q20Factor, select1$Q2dFactor)
```

# Reduction of CO2 emissions

```{r}
(emisij <- as.data.frame.matrix(table(select1$Q20Factor, select1$Q2eFactor)))
emisijdf <- data.frame(sector = select1$Q20Factor, duration = select1$Q2eFactor)
emisijdf <- emisijdf %>% drop_na()
emisijdfgroup <- emisijdf %>% 
  group_by(sector, duration) %>% 
  summarise(count = n()) %>% 
  drop_na()

ggplot(emisijdfgroup, aes(x=sector, y=duration)) + 
  geom_point(aes(size = count), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 20, guide = FALSE) +
  geom_text(aes(
    y = as.numeric(as.factor(duration)) - count/34, label = count),
    vjust = 2,
    colour = "black",
    size = 4
  ) + 
  xlab("Sektor") + ylab("Duration of investment") +
  labs(caption=paste("Number of responses :",nrow(emisijdf)))

fisher.test(select1$Q20Factor, select1$Q2eFactor)
```

# Use of renewable energy sources

```{r}
(virov <- as.data.frame.matrix(table(select1$Q20Factor, select1$Q2fFactor)))
virovdf <- data.frame(sector = select1$Q20Factor, duration = select1$Q2fFactor)
virovdf <- virovdf %>% drop_na()
virovdfgroup <- virovdf %>% 
  group_by(sector, duration) %>% 
  summarise(count = n()) %>% 
  drop_na()

ggplot(virovdfgroup, aes(x=sector, y=duration)) + 
  geom_point(aes(size = count), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 20, guide = FALSE) +
  geom_text(aes(
    y = as.numeric(as.factor(duration)) - count/34, label = count),
    vjust = 3,
    colour = "black",
    size = 4
  ) + 
  xlab("Sektor") + ylab("Duration of investment") +
  labs(caption=paste("Number of responses :",nrow(virovdf)))

fisher.test(select1$Q20Factor, select1$Q2fFactor)
```

# Paperless business

```{r}
(brezpap <- as.data.frame.matrix(table(select1$Q20Factor, select1$Q2gFactor)))
brezpapdf <- data.frame(sector = select1$Q20Factor, duration = select1$Q2gFactor)
brezpapdf <- brezpapdf %>% drop_na()
brezpapdfgroup <- brezpapdf %>% 
  group_by(sector, duration) %>% 
  summarise(count = n()) %>% 
  drop_na()

ggplot(brezpapdfgroup, aes(x=sector, y=duration)) + 
  geom_point(aes(size = count), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 20, guide = FALSE) +
  geom_text(aes(
    y = as.numeric(as.factor(duration)) - count/34, label = count),
    vjust = 3,
    colour = "black",
    size = 4
  ) + 
  xlab("Sektor") + ylab("Duration of investment") +
  labs(caption=paste("Number of responses :",nrow(brezpapdf)))

fisher.test(select1$Q20Factor, select1$Q2gFactor)
```

# Work from home

```{r}
(doma <- as.data.frame.matrix(table(select1$Q20Factor, select1$Q2hFactor)))
domadf <- data.frame(sector = select1$Q20Factor, duration = select1$Q2hFactor)
domadf <- domadf %>% drop_na()
domadfgroup <- domadf %>% 
  group_by(sector, duration) %>% 
  summarise(count = n()) %>% 
  drop_na()

ggplot(domadfgroup, aes(x=sector, y=duration)) + 
  geom_point(aes(size = count), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 20, guide = FALSE) +
  geom_text(aes(
    y = as.numeric(as.factor(duration)) - count/34, label = count),
    vjust = 3,
    colour = "black",
    size = 4
  ) + 
  xlab("Sektor") + ylab("Duration of investment") +
  labs(caption=paste("Number of responses :",nrow(domadf)))

fisher.test(select1$Q20Factor, select1$Q2hFactor)
```

# Car sharing

```{r}
(carsh <- as.data.frame.matrix(table(select1$Q20Factor, select1$Q2iFactor)))
carshdf <- data.frame(sector = select1$Q20Factor, duration = select1$Q2iFactor)
carshdf <- carshdf %>% drop_na()
carshdfgroup <- carshdf %>% 
  group_by(sector, duration) %>% 
  summarise(count = n()) %>% 
  drop_na()

ggplot(carshdfgroup, aes(x=sector, y=duration)) + 
  geom_point(aes(size = count), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 20, guide = FALSE) +
  geom_text(aes(
    y = as.numeric(as.factor(duration)) - count/34, label = count),
    vjust = 3,
    colour = "black",
    size = 4
  ) + 
  xlab("Sektor") + ylab("Duration of investment") +
  labs(caption=paste("Number of responses :",nrow(carshdf)))

fisher.test(select1$Q20Factor, select1$Q2iFactor)
```


