---
title: "Pearson Chi2"
output:
  html_document:
#    code_folding: hide
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 120)
#install.packages("ggpubr")
library(ggpubr)
#install.packages("DescTools")
library(DescTools)
```


```{r}
mydata <- read.table("/cloud/project/Lectures/L1/Cats/Cats.csv", header=TRUE, sep=";")
head(mydata)
```

Description

- Training; 0:Food, 1: Love
- Outcome; 0: NO, 1: YES

```{r}
mydata$TrainingFactor <- factor(mydata$Training, 
                                levels = c(0, 1), 
                                labels = c("Food", "Love"))

mydata$OutcomeFactor <- factor(mydata$Outcome, 
                               levels = c(0, 1), 
                               labels = c("NO", "YES"))
   
head(mydata)
```


```{r}
cont_table <- as.data.frame(table(mydata$TrainingFactor, mydata$OutcomeFactor))
colnames(cont_table) <- c("Outcome", "Training", "Freq")
cont_table
```

### Person's Chi2 test
```{r}
results <- chisq.test(mydata$TrainingFactor, mydata$OutcomeFactor, 
                      correct = TRUE)

results

addmargins(results$observed)

round(results$expected, 2)

round(results$res, 2)
```

```{r}
addmargins(round(prop.table(results$observed), 3))
addmargins(round(prop.table(results$observed, 1), 3), 2) 
addmargins(round(prop.table(results$observed, 2), 3), 1) 
```




```{r}
library(DescTools)
CramerV(mydata$TrainingFactor, mydata$OutcomeFactor)
```


### Fisher's exact probability test
```{r}
fisher.test(mydata$TrainingFactor, mydata$OutcomeFactor)
```