---
title: "The hypothesis about the arithmetic mean"
output:
  html_document:
#    code_folding: hide
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 120)
#install.packages("ggplot2")
library(ggplot2)
#install.packages("dplyr")
library(dplyr)
#install.packages("car")
library(car)
#install.packages("formatR")
library(formatR)
#install.packages("pastecs")
library(pastecs)
#install.packages("psych")
library(psych)
```

```{r}
mydata <- read.table("/cloud/project/Lectures/L1/Body mass/Body mass.csv", header=TRUE, sep=";", dec=",")
head(mydata)
```
Description:

- ID: Person ID
- Mass: Body mass in kg

```{r}
library(pastecs)
round(stat.desc(mydata$Mass), 3)
```



```{r}
library(ggplot2)
ggplot(mydata, aes(x=Mass)) +
  geom_histogram(position = "identity", binwidth = 5, colour = "black") +
  xlab("Body mass in kg")
```



```{r}
library(ggplot2)
ggplot(mydata, aes(y=Mass)) +
  geom_boxplot()
```

```{r}
mean(mydata$Mass)
sd(mydata$Mass)
```


# Confidence interval
```{r}
ybar = mean(mydata$Mass); sd = sd(mydata$Mass); n = nrow(mydata)

se = sd/sqrt(n)

ybar_lower = ybar + qt(0.025, df=n-1)*se
ybar_upper = ybar + qt(0.975, df=n-1)*se

ybar_lower
ybar_upper
```


### Parametric test
```{r}
t.test(mydata$Mass,
       mu = 59.5,
       alternative = "two.sided")
```

### Non-parametric
```{r}
wilcox.test(mydata$Mass,
            mu = 58.3,
            correct = FALSE)
```

